### ISSUE TITLE
jsmediatags is really slow when to get images !

### ISSUE THREAD

**Issue by baloone** [nt1m/HTML5AudioPlayer#113]
Maybe we should look for another lib.

**Comment by baloone** [comment]
At least we could parse an album cover once per album instead of once per song

**Comment by nt1m** [comment]
Can you record a performance profile with the Chrome or Firefox DevTools and export it (make sure you don't have any other tab opened) ? Thanks!

**Comment by baloone** [comment]
here's the link to the file
https://mega.nz/#!tkJHBboK!0YOtaEOySWfrmqw3ID5J0ykQfwVzhVE-A8lhh4fEdjQ

**Comment by Borewit** [comment]
You could try [music-metadata](https://github.com/Borewit/music-metadata).

**Comment by baloone** [comment]
this issue is already solved, thanks
