### ISSUE TITLE
Won't play back any mp3 (web build)

### ISSUE THREAD

**Issue by Happy-Ferret** [nt1m/HTML5AudioPlayer#117]
While the web build plays videos just fine, it doesn't appear to ever actually load audio files.
At least not mp3 music.

What I've been doing is download a few mp3s from Youtube. While those play fine in every other media player, they won't play here. The sidebar will just sit there saying "Loading..."

**Comment by nt1m** [comment]
@MohIceAge ^

**Comment by baloone** [comment]
FIxed !
