### ISSUE TITLE
Uncaught InvalidStateError: Failed to execute 'createMediaElementSource'

### ISSUE THREAD

**Issue by DaniellMesquita** [nt1m/HTML5AudioPlayer#12]
Each time that I press Play button, the console triggers this error:
"Uncaught InvalidStateError: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode"

**Comment by nt1m** [comment]
Works fine on Firefox, what browser do you use ?

**Comment by DaniellMesquita** [comment]
Google Chrome 43.0.2357.132 in Windows 10 RTM x64.

**Comment by DaniellMesquita** [comment]
Too, works fine here, but console triggers this error.

**Comment by kaygude** [comment]
Google Chrome Version 45.0.2454.101 in Ubuntu also have same issue and I am not able to play song,Is there any solution for this

**Comment by danimesq** [comment]
@nt1m This is very focused in Mozilla Firefox, but need tests on Google Chrome.
