### ISSUE TITLE
Can control volume before play

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#14]
Will be nice bcause you're planning to add video support, to user can control volume before play. This will be usefull for musics and videos. For music example, imagine a people with an earphone or headset loading a too loud music and can't set volume to 50%. For video example, imagine an people loading an porn video that starts with "ahn oh yes uhn" sounds, at 02:00 AM and can't turn off the volume before this embarassing sounds.

**Comment by nt1m** [comment]
Agree. Should be easy enough : 
Just remove `, .disabled #volume-control` from https://github.com/nt1m/HTML5AudioPlayer/blob/master/css/style.css#L207

Do you want to submit a PR ?

**Comment by danimesq** [comment]
Yes. Issue fixed with https://github.com/nt1m/HTML5AudioPlayer/pull/23 pull request.
You can Label+Close this issue now.
