### ISSUE TITLE
Can use "Repeat" and "Speed" buttons ever

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#16]
My suggestion is to user can use this buttons before loading any media.

**Comment by nt1m** [comment]
These don't work properly anyway.

**Comment by danimesq** [comment]
I understand that these buttons can not work properly, But for now, user can do pointer events before loading any sound, and in future when these buttons will work like a charm, this previous commit will be usefull. Here is in https://github.com/nt1m/HTML5AudioPlayer/pull/24 pull request.
