### ISSUE TITLE
Go to next/previous file in list

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#17]
Adding these 2 buttons and their functions, you'll achieve an very nice function that the WMP can't do.

**Comment by nt1m** [comment]
@Plasmmer This is very easy to add, but I don't think we have enough space for more buttons.

Do you have suggestions where to add the buttons ?

**Comment by nt1m** [comment]
Double click the `<<` or `>>` icons to go to the previous/next file.

**Comment by danimesq** [comment]
I don't think double-click as the only option is nice. In the desktop, in my opinion, it is a need.

**Comment by nt1m** [comment]
@Plasmmer I'm fine with adding buttons, but I'm not sure where to add them, the controls bar is quite cluttered already.

**Comment by danimesq** [comment]
Theres also space to put the volume percentage:
<img src="http://image.prntscr.com/image/4c23ccbe7bbe4b1f82ff8b2d29513426.png"/>

**Comment by nt1m** [comment]
@Plasmmer There are lots of buttons there already. I don't think adding more is a good solution.

Perhaps we could remove "Stop" (it's not very useful with pause and remove from playlist anyway).
We could also remove "fast forward/rewind" since you can simply use the left arrow/right arrow.

**Comment by danimesq** [comment]
Not. We can simple do like WMP: 
<img src="http://image.prntscr.com/image/da3107ac18fd48a49d5a2fa2ff45df2c.png"/>

**Comment by nt1m** [comment]
@Plasmmer Sounds good. I would remove the stop button as well, it doesn't really have a strong utility IMO.

**Comment by danimesq** [comment]
I agree. It will give space to important buttons if we reduce the width of the window, such as the Menu button.
