### ISSUE TITLE
Bug when push the progress bar

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#18]
When push progress bar, other elements in page are selected. This issue is on my Google Chrome 43.0.2357.132 in Windows 10 RTM x64.

**Comment by nt1m** [comment]
This should be easy to fix : 

<pre>
::-moz-selection {
  background: none;
}
::selection {
  background: none;
}
</pre>

**Comment by danimesq** [comment]
Good tip. Sorry, I've already fixed at morning but was can't uploaded because a party. I've uploaded now and sent as pull request.
Using this trick:
body {
-webkit-user-select: none;
-moz-user-select: none;
}

**Comment by danimesq** [comment]
Initial work has been uploaded: https://github.com/nt1m/HTML5AudioPlayer/pull/19.
Soon I will add the unprefixed propertie `user-select: none`.

**Comment by danimesq** [comment]
Final work for this issue has been uploaded: https://github.com/nt1m/HTML5AudioPlayer/pull/25.
Now you can add a `bug` label and close this issue.
