### ISSUE TITLE
Can drag the media's status bar

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#20]
Now, user only can click in each point that need reach, but can't drag status bar's button to select the state of time. I think that this will need jQuery, correct?

**Comment by nt1m** [comment]
This is easy to implement without jQuery, although this project is no longer my priority now.

**Comment by danimesq** [comment]
@nt1m 
This is very slow, unlike the volume range.

**Comment by nt1m** [comment]
Yeah, you need to mouse over the progress bar atm. Unfortunately, there's no nice way to fix this.
