### ISSUE TITLE
Change the repo name once it gets video support

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#26]
You're planning to add video support as seen in https://github.com/nt1m/HTML5AudioPlayer/issues/9 improvement issue, correct? This will be from audio player to a media player. Then, Aurora Media Player will be a very nice name to be partner of Altaica OS. Aurora instead of using generic HTML5 name.

**Comment by nt1m** [comment]
I want to keep the name generic, because this is meant to be an open-source repo, not a product (which is in fact why there is no branding in the player). But I guess I'll change this to HTML5MediaPlayer once this gets video support.

**Comment by danimesq** [comment]
You can also make an open-source product for Altaica, like VLC Media Player, Blender, Pidgin and Gimp.
