### ISSUE TITLE
3 state loop button

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#30]
Do an arrow icon with divisorie. When user click on loop button, open a dropdown menu to choose between play current audio or whole playlist. Include an state icon in loop button showing if will loop the current audio or whole playlist.

**Comment by nt1m** [comment]
You seem to be requesting something very specific here. The intended behaviour is that the button loops the whole playlist.

**Comment by nt1m** [comment]
Default: Don't loop playlist
Click once: Loops whole playlist (icon gets colored)
Click once again: loops one song (icon gets colored + badge)
Click again: go back to not looping

**Comment by nt1m** [comment]
@Plasmmer Does it work well for you ?

**Comment by danimesq** [comment]
The current state hover tooltip is missing.

**Comment by danimesq** [comment]
This opens the need of a multiple playlists function.
Also, please join http://zeronet.io
