### ISSUE TITLE
App for Windows Universal Platform

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#36]

**Comment by nt1m** [comment]
Electron covers Windows.

**Comment by danimesq** [comment]
Please release the app for UWP, for developers that have sideload function enabled.

**Comment by danimesq** [comment]
Shouldn't it use Electron-Cordova? As it would cover both mobile and desktop.
Reference: https://github.com/nt1m/media-player/issues/168
