### ISSUE TITLE
App for Android

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#40]

**Comment by danimesq** [comment]
@nt1m , do you authorize me to publish this app in my developer page on Google Play Store?

**Comment by nt1m** [comment]
@Plasmmer As long as you add a link back to the github repo in the description, feel free to publish it.

Something like:

"Source code: https://github.com/nt1m/HTML5AudioPlayer/"

**Comment by nt1m** [comment]
I'm going to close this so we can do everything in #89

**Comment by danimesq** [comment]
> @Plasmmer As long as you add a link back to the github repo in the description, feel free to publish it.
> 
> Something like:
> 
> "Source code: https://github.com/nt1m/HTML5AudioPlayer/"

Hey, do you have an Google Play developer account?
I agree to keep your credits if I publish it by myself; but I would like to help you to publish it by yourself as I think its the better way.

**Comment by danimesq** [comment]
Reference: https://github.com/nt1m/media-player/issues/168
