### ISSUE TITLE
previsualizer/placeholder appearing after some events

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#57]
When:
1. Pause;
2. Stop;
3. Play again;
4. The previsualizer/placeholder keep appearing togheter the visualizer.

<img src="http://image.prntscr.com/image/05dc3d584b8c43638ee0b0a3e55c5811.png"/>

@nt1m please flag this issue as bug, then I'll edit the title. I'll work to mitigate and solve this conflict.

**Comment by nt1m** [comment]
Does 94f19cb4c2cca8dc01fef3fb07a66017bc400fbb fix the problem ?

**Comment by danimesq** [comment]
The problem is now fixed. Thanks.
