### ISSUE TITLE
Custom themes system

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#65]
User will can upload custom CSS or (maybe) change the CSS via the app.
Also a "pre-installed" list with custom CSS/skins for the player.

**Comment by nt1m** [comment]
Can you elaborate?

**Comment by Plasmmer** [comment]
User will can upload custom CSS or (maybe) change the CSS via the app.
Also a "pre-installed" list with custom CSS/skins for the player.

**Comment by danimesq** [comment]
The description of this issue has been updated.
