### ISSUE TITLE
Display more ID3 properties

### ISSUE THREAD

**Issue by nt1m** [nt1m/HTML5AudioPlayer#67]
We currently have:

            "title": result.slice(4, 64).replace(/[\0]/g, ""),
            "artist": result.slice(64, 124).replace(/[\0]/g, ""),
            "album": result.slice(124, 184).replace(/[\0]/g, ""),
            "speed_list": ["unset", "slow", "medium", "fast", "hardcore"],
            "speed": this.speed_list[parseInt(result.slice(184, 185))],
            "genre": result.slice(185, 215).replace(/[\0]/g, ""),
            "start-time": result.slice(215, 221).replace(/[\0]/g, ""),
            "end-time": result.slice(221, 227).replace(/[\0]/g, "")

But we only use title and artist right now.

**Comment by danimesq** [comment]
Also, show the album cover art as suggested in #49.

**Comment by danimesq** [comment]
@nt1m, why close this issue?

**Comment by nt1m** [comment]
The tooltip now includes the album and the genre.
