### ISSUE TITLE
Some problems with the latest update in Chrome

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#76]
To fix:
- [x] The repeat button don't have anymore a good active effect (now is the same as the hover effect)
- [x] The media buttons don't have a good contrast with the rest of colors

**Comment by nt1m** [comment]
>  The repeat button don't have anymore a good active effect (now is the same as the hover effect)

Do you want to give it a try to fix this bug?
https://github.com/nt1m/HTML5AudioPlayer/blob/gh-pages/css/controls.css#L43

> The media buttons don't have a good contrast with the rest of colors

Ah, yes, didn't test in Chrome.

>  Invertion filter instead of own colors for each theme

I already use an inversion filter.

**Comment by danimesq** [comment]
> Do you want to give it a try to fix this bug?
> https://github.com/nt1m/HTML5AudioPlayer/blob/gh-pages/css/controls.css#L43
I don't know how fix it, because I don't understand so much about .svg graphics.

> Ah, yes, didn't test in Chrome.
I'll test it in Firefox and try to make it work like in Chrome.

> I already use an inversion filter.
As I expect you can see, I'm listing problems in this issue, and I'm not suggesting. I already know you used a invertion filter, and is about it I'm talking.

I need to talk you in Hangouts.

**Comment by danimesq** [comment]
Yes, it works very different in Firefox.

Chrome:
<img src="http://image.prntscr.com/image/630d9ac1818d43ea8271ed19a44b9862.png"/>

Firefox:
<img src="http://image.prntscr.com/image/8fd23ae4d21343ae918507b8dbeef782.png"/>
