### ISSUE TITLE
More runtimes

### ISSUE THREAD

**Issue by nt1m** [nt1m/HTML5AudioPlayer#89]
Mobile: Use Cordova

Other:
- Watches
- TV

**Comment by nt1m** [comment]
https://cordova.apache.org/

**Comment by danimesq** [comment]
We can also support Tizen and Firefox Marketplace in the future.
https://wiki.tizen.org/wiki/Cordova

**Comment by danimesq** [comment]
Shouldn't this issue be moved into https://github.com/nt1m/media-player/issues/168?

Or better, add https://github.com/nt1m/media-player/issues/168 to the description as it covers both mobile and desktop?
