### ISSUE TITLE
[Electron] Fix icon and names in some places

### ISSUE THREAD

**Issue by nt1m** [nt1m/HTML5AudioPlayer#92]
In some places the "Electron" name/icon still appears.

**Comment by baloone** [comment]
More details ?

**Comment by nt1m** [comment]
@MohIceAge You can still see "Electron" as app name in some places.
<img width="1024" alt="win-32-electron-app" src="https://cloud.githubusercontent.com/assets/1795135/24355051/58bfb022-12ec-11e7-9afd-1f173fabc9bb.png">

**Comment by nt1m** [comment]
@MohIceAge Yep, still says "Electron" even after the commit.

**Comment by nt1m** [comment]
59e4bc3 fixes it
