### ISSUE TITLE
[Electron][Windows] Create thumbnail buttons

### ISSUE THREAD

**Issue by nt1m** [nt1m/HTML5AudioPlayer#93]
Quick actions from taskbar context menu:
Thumb bar buttons (using [app.setThumbarButtons](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetthumbarbuttonsbuttons-windows)):
- Play/Pause
- Previous song/Next song
- Shuffle
- Loop one song

Also, display the playlist or recently opened files (in the recent category)

**Comment by danimesq** [comment]
Please see #102. Its better to be introduced in the window thumbnail.
As jumplists, you can put the historic of played files, and the "play all" button.

**Comment by nt1m** [comment]
Recently opened files opened directly from the file system are now shown.

**Comment by danimesq** [comment]
Can you release it?

**Comment by nt1m** [comment]
@Plasmmer I can't do a Windows release without #97 unfortunately.
Though, you can do "npm start" on Windows to see this working.
