### ISSUE TITLE
[Electron] Ability to register Media Player as handler for music and video

### ISSUE THREAD

**Issue by nt1m** [nt1m/HTML5AudioPlayer#98]
We should be able to open music/video files directly from the File explorer without having to launch the audio player first.

**Comment by danimesq** [comment]
@nt1m 
Too, create a icon in these files.
If have a visualization (music with album art or video), show it plus the badge of the app.

**Comment by danimesq** [comment]
@nt1m 
Can you do a release?

**Comment by nt1m** [comment]
@Plasmmer It should be easier if you just run `npm run pack-win` on your machine. Right now, I don't have anything that can generate a working windows installer.

Note that on Windows, Open With Media Player is supported, but it doesn't actually register the app as handler.
