### ISSUE TITLE
[Electron] When close the last music and try plain again, won't works

### ISSUE THREAD

**Issue by danimesq** [nt1m/HTML5AudioPlayer#99]

**Comment by nt1m** [comment]
I can't reproduce, do you get any error in the console (Ctrl+Shift+K) ?

**Comment by danimesq** [comment]
It don't works on Windows.

**Comment by danimesq** [comment]
Oh, it also don't works on web. And the console is empty.

**Comment by nt1m** [comment]
@Plasmmer can you try again ? I think my last commit may have fixed it

**Comment by danimesq** [comment]
Isn't working yet.

**Comment by nt1m** [comment]
@Plasmmer do you have a sample audio file?

**Comment by danimesq** [comment]
You can download as mp3 from Youtube:
https://www.youtube.com/watch?v=PGNiXGX2nLU

**Comment by nt1m** [comment]
@Plasmmer I can't reproduce.

Can you provide:
- Step by step instructions to reproduce the bug
- a sample MP3 file
?
Thanks!

**Comment by nt1m** [comment]
@Plasmmer I think I just fixed the issue, you might want to try again.
